CREATE TABLE usuario (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(128) NOT NULL
);

CREATE TABLE produto (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	nome VARCHAR(128) NOT NULL,
	descricao VARCHAR(512) NOT NULL,
	preco NUMERIC(8,2) NOT NULL
);

CREATE TABLE loja (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	nome VARCHAR(128) NOT NULL,
	endereco VARCHAR(256) NOT NULL
);